name: Build & Pack releases/garaio/*

on:
  push:
    branches:
      - release/garaio/*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack -c Release --no-build --include-symbols --include-source --version-suffix beta
    - name: Publish    
      uses: actions/upload-artifact@v2
      with:
        name: NuGet Package (consul)
        path: dist/Consul*
